-- Migration: Database index audit — all 73 tables
-- Adds missing indexes on foreign key columns, columns used in WHERE/ORDER BY clauses,
-- and health check queue depth queries.

-- Priority 1: Health check & high-traffic route indexes
CREATE INDEX IF NOT EXISTS "cassidy_jobs_status_idx" ON "cassidy_jobs" ("status");
CREATE INDEX IF NOT EXISTS "cassidy_jobs_advisor_id_idx" ON "cassidy_jobs" ("advisor_id");
CREATE INDEX IF NOT EXISTS "cassidy_jobs_client_id_idx" ON "cassidy_jobs" ("client_id");
CREATE INDEX IF NOT EXISTS "cassidy_jobs_created_at_idx" ON "cassidy_jobs" ("created_at");
CREATE INDEX IF NOT EXISTS "approval_items_created_at_idx" ON "approval_items" ("created_at");
CREATE INDEX IF NOT EXISTS "tasks_category_status_due_date_idx" ON "tasks" ("category", "status", "due_date");

-- Priority 2: Legacy table FK indexes
CREATE INDEX IF NOT EXISTS "client_team_members_client_id_idx" ON "client_team_members" ("client_id");
CREATE INDEX IF NOT EXISTS "client_team_members_associate_id_idx" ON "client_team_members" ("associate_id");
CREATE INDEX IF NOT EXISTS "households_advisor_id_idx" ON "households" ("advisor_id");
CREATE INDEX IF NOT EXISTS "households_primary_client_id_idx" ON "households" ("primary_client_id");
CREATE INDEX IF NOT EXISTS "household_members_household_id_idx" ON "household_members" ("household_id");
CREATE INDEX IF NOT EXISTS "household_members_client_id_idx" ON "household_members" ("client_id");
CREATE INDEX IF NOT EXISTS "accounts_client_id_idx" ON "accounts" ("client_id");
CREATE INDEX IF NOT EXISTS "accounts_household_id_idx" ON "accounts" ("household_id");
CREATE INDEX IF NOT EXISTS "transactions_account_id_idx" ON "transactions" ("account_id");
CREATE INDEX IF NOT EXISTS "activities_advisor_id_idx" ON "activities" ("advisor_id");
CREATE INDEX IF NOT EXISTS "activities_client_id_idx" ON "activities" ("client_id");
CREATE INDEX IF NOT EXISTS "documents_client_id_idx" ON "documents" ("client_id");
CREATE INDEX IF NOT EXISTS "compliance_items_client_id_idx" ON "compliance_items" ("client_id");
CREATE INDEX IF NOT EXISTS "compliance_items_advisor_id_idx" ON "compliance_items" ("advisor_id");
CREATE INDEX IF NOT EXISTS "life_events_client_id_idx" ON "life_events" ("client_id");
CREATE INDEX IF NOT EXISTS "trigger_actions_life_event_id_idx" ON "trigger_actions" ("life_event_id");
CREATE INDEX IF NOT EXISTS "document_checklist_client_id_idx" ON "document_checklist" ("client_id");
CREATE INDEX IF NOT EXISTS "workflow_templates_advisor_id_idx" ON "workflow_templates" ("advisor_id");
CREATE INDEX IF NOT EXISTS "client_workflows_client_id_idx" ON "client_workflows" ("client_id");
CREATE INDEX IF NOT EXISTS "client_workflows_template_id_idx" ON "client_workflows" ("template_id");
CREATE INDEX IF NOT EXISTS "compliance_reviews_client_id_idx" ON "compliance_reviews" ("client_id");
CREATE INDEX IF NOT EXISTS "compliance_reviews_advisor_id_idx" ON "compliance_reviews" ("advisor_id");
CREATE INDEX IF NOT EXISTS "compliance_review_events_review_id_idx" ON "compliance_review_events" ("review_id");
CREATE INDEX IF NOT EXISTS "report_templates_advisor_id_idx" ON "report_templates" ("advisor_id");
CREATE INDEX IF NOT EXISTS "report_artifacts_advisor_id_idx" ON "report_artifacts" ("advisor_id");
CREATE INDEX IF NOT EXISTS "report_artifacts_client_id_idx" ON "report_artifacts" ("client_id");
CREATE INDEX IF NOT EXISTS "report_artifacts_created_at_idx" ON "report_artifacts" ("created_at");
CREATE INDEX IF NOT EXISTS "report_artifact_versions_artifact_id_idx" ON "report_artifact_versions" ("artifact_id");
CREATE INDEX IF NOT EXISTS "calculator_runs_advisor_id_idx" ON "calculator_runs" ("advisor_id");
CREATE INDEX IF NOT EXISTS "calculator_runs_client_id_idx" ON "calculator_runs" ("client_id");
CREATE INDEX IF NOT EXISTS "diagnostic_results_client_id_idx" ON "diagnostic_results" ("client_id");
CREATE INDEX IF NOT EXISTS "diagnostic_results_config_id_idx" ON "diagnostic_results" ("config_id");
CREATE INDEX IF NOT EXISTS "login_events_user_id_idx" ON "login_events" ("user_id");
CREATE INDEX IF NOT EXISTS "zoom_recordings_meeting_id_idx" ON "zoom_recordings" ("meeting_id");
CREATE INDEX IF NOT EXISTS "meeting_transcripts_meeting_id_idx" ON "meeting_transcripts" ("meeting_id");
CREATE INDEX IF NOT EXISTS "alert_config_advisor_id_idx" ON "alert_config" ("advisor_id");
CREATE INDEX IF NOT EXISTS "portfolio_targets_client_id_idx" ON "portfolio_targets" ("client_id");
CREATE INDEX IF NOT EXISTS "assessments_client_id_idx" ON "assessments" ("client_id");
CREATE INDEX IF NOT EXISTS "assessments_advisor_id_idx" ON "assessments" ("advisor_id");
CREATE INDEX IF NOT EXISTS "assessment_pdfs_assessment_id_idx" ON "assessment_pdfs" ("assessment_id");
CREATE INDEX IF NOT EXISTS "insights_client_id_idx" ON "insights" ("client_id");
CREATE INDEX IF NOT EXISTS "insights_advisor_id_idx" ON "insights" ("advisor_id");
CREATE INDEX IF NOT EXISTS "investor_profile_versions_profile_id_idx" ON "investor_profile_versions" ("profile_id");
CREATE INDEX IF NOT EXISTS "fact_finder_responses_advisor_id_idx" ON "fact_finder_responses" ("advisor_id");
CREATE INDEX IF NOT EXISTS "fact_finder_responses_client_id_idx" ON "fact_finder_responses" ("client_id");
CREATE INDEX IF NOT EXISTS "fact_finder_responses_definition_id_idx" ON "fact_finder_responses" ("definition_id");
CREATE INDEX IF NOT EXISTS "monte_carlo_scenarios_client_id_idx" ON "monte_carlo_scenarios" ("client_id");
CREATE INDEX IF NOT EXISTS "scenario_events_scenario_id_idx" ON "scenario_events" ("scenario_id");
CREATE INDEX IF NOT EXISTS "alternative_assets_client_id_idx" ON "alternative_assets" ("client_id");
CREATE INDEX IF NOT EXISTS "trust_relationships_trust_id_idx" ON "trust_relationships" ("trust_id");
CREATE INDEX IF NOT EXISTS "gift_history_client_id_idx" ON "gift_history" ("client_id");
CREATE INDEX IF NOT EXISTS "screening_configs_advisor_id_idx" ON "screening_configs" ("advisor_id");
CREATE INDEX IF NOT EXISTS "charitable_contributions_account_id_idx" ON "charitable_contributions" ("account_id");
CREATE INDEX IF NOT EXISTS "business_valuations_business_entity_id_idx" ON "business_valuations" ("business_entity_id");
CREATE INDEX IF NOT EXISTS "charitable_grants_account_id_idx" ON "charitable_grants" ("account_id");
CREATE INDEX IF NOT EXISTS "charitable_goals_client_id_idx" ON "charitable_goals" ("client_id");
CREATE INDEX IF NOT EXISTS "buy_sell_agreements_business_entity_id_idx" ON "buy_sell_agreements" ("business_entity_id");
CREATE INDEX IF NOT EXISTS "exit_plan_milestones_business_entity_id_idx" ON "exit_plan_milestones" ("business_entity_id");
CREATE INDEX IF NOT EXISTS "daf_transactions_daf_account_id_idx" ON "daf_transactions" ("daf_account_id");

-- Priority 3: Remaining FK columns without indexes
CREATE INDEX IF NOT EXISTS "tasks_meeting_id_idx" ON "tasks" ("meeting_id");
CREATE INDEX IF NOT EXISTS "tasks_assignee_id_idx" ON "tasks" ("assignee_id");
CREATE INDEX IF NOT EXISTS "report_artifacts_template_id_idx" ON "report_artifacts" ("template_id");
CREATE INDEX IF NOT EXISTS "report_artifacts_household_id_idx" ON "report_artifacts" ("household_id");
CREATE INDEX IF NOT EXISTS "report_artifacts_created_by_idx" ON "report_artifacts" ("created_by");
CREATE INDEX IF NOT EXISTS "report_artifact_versions_edited_by_idx" ON "report_artifact_versions" ("edited_by");
CREATE INDEX IF NOT EXISTS "calculator_runs_household_id_idx" ON "calculator_runs" ("household_id");
CREATE INDEX IF NOT EXISTS "calculator_runs_created_by_idx" ON "calculator_runs" ("created_by");
CREATE INDEX IF NOT EXISTS "investor_profile_versions_question_schema_id_idx" ON "investor_profile_versions" ("question_schema_id");
CREATE INDEX IF NOT EXISTS "fact_finder_responses_household_id_idx" ON "fact_finder_responses" ("household_id");
CREATE INDEX IF NOT EXISTS "cassidy_jobs_household_id_idx" ON "cassidy_jobs" ("household_id");
CREATE INDEX IF NOT EXISTS "trust_relationships_person_client_id_idx" ON "trust_relationships" ("person_client_id");
CREATE INDEX IF NOT EXISTS "gift_history_trust_id_idx" ON "gift_history" ("trust_id");

-- Priority 4: All remaining FK columns across the full schema
CREATE INDEX IF NOT EXISTS "performance_household_id_idx" ON "performance" ("household_id");
CREATE INDEX IF NOT EXISTS "custodial_changes_matched_client_id_idx" ON "custodial_changes" ("matched_client_id");
CREATE INDEX IF NOT EXISTS "custodial_changes_matched_account_id_idx" ON "custodial_changes" ("matched_account_id");
CREATE INDEX IF NOT EXISTS "custodial_changes_approval_item_id_idx" ON "custodial_changes" ("approval_item_id");
CREATE INDEX IF NOT EXISTS "fact_finder_responses_reviewed_by_idx" ON "fact_finder_responses" ("reviewed_by");
CREATE INDEX IF NOT EXISTS "idx_conversation_client" ON "conversation_turns" ("client_id");
CREATE INDEX IF NOT EXISTS "idx_conversation_job" ON "conversation_turns" ("job_id");
CREATE INDEX IF NOT EXISTS "idx_ds_questionnaire_id" ON "discovery_sessions" ("questionnaire_id");
CREATE INDEX IF NOT EXISTS "idx_ds_meeting_id" ON "discovery_sessions" ("meeting_id");
CREATE INDEX IF NOT EXISTS "trusts_advisor_id_idx" ON "trusts" ("advisor_id");
CREATE INDEX IF NOT EXISTS "estate_exemptions_advisor_id_idx" ON "estate_exemptions" ("advisor_id");
CREATE INDEX IF NOT EXISTS "withdrawal_requests_account_id_idx" ON "withdrawal_requests" ("account_id");
CREATE INDEX IF NOT EXISTS "aml_screening_advisor_id_idx" ON "aml_screening_results" ("advisor_id");
CREATE INDEX IF NOT EXISTS "kyc_review_schedules_advisor_id_idx" ON "kyc_review_schedules" ("advisor_id");
CREATE INDEX IF NOT EXISTS "edd_records_advisor_id_idx" ON "edd_records" ("advisor_id");
CREATE INDEX IF NOT EXISTS "kyc_audit_log_advisor_id_idx" ON "kyc_audit_log" ("advisor_id");
CREATE INDEX IF NOT EXISTS "pre_case_validations_advisor_id_idx" ON "pre_case_validations" ("advisor_id");
CREATE INDEX IF NOT EXISTS "nigo_items_client_id_idx" ON "nigo_items" ("client_id");
CREATE INDEX IF NOT EXISTS "nigo_items_account_id_idx" ON "nigo_items" ("account_id");
CREATE INDEX IF NOT EXISTS "charitable_accounts_advisor_id_idx" ON "charitable_accounts" ("advisor_id");
CREATE INDEX IF NOT EXISTS "tax_lots_holding_id_idx" ON "tax_lots" ("holding_id");
CREATE INDEX IF NOT EXISTS "direct_index_portfolios_account_id_idx" ON "direct_index_portfolios" ("account_id");
CREATE INDEX IF NOT EXISTS "wash_sale_events_sell_account_id_idx" ON "wash_sale_events" ("sell_account_id");
CREATE INDEX IF NOT EXISTS "wash_sale_events_buy_account_id_idx" ON "wash_sale_events" ("buy_account_id");
CREATE INDEX IF NOT EXISTS "nigo_records_account_id_idx" ON "nigo_records" ("account_id");
CREATE INDEX IF NOT EXISTS "flp_structures_advisor_id_idx" ON "flp_structures" ("advisor_id");
CREATE INDEX IF NOT EXISTS "exit_milestones_advisor_id_idx" ON "exit_milestones" ("advisor_id");
CREATE INDEX IF NOT EXISTS "daf_accounts_advisor_id_idx" ON "daf_accounts" ("advisor_id");
CREATE INDEX IF NOT EXISTS "crt_advisor_id_idx" ON "charitable_remainder_trusts" ("advisor_id");
CREATE INDEX IF NOT EXISTS "qcd_records_advisor_id_idx" ON "qcd_records" ("advisor_id");
