import type { Express } from "express";
import { type Server } from "http";
import express from "express";
import path from "path";
import { seedDatabase } from "./seed";
import { registerAuthRoutes } from "./routes/auth";
import { registerClientRoutes } from "./routes/clients";
import { registerMeetingRoutes } from "./routes/meetings";
import { registerTaskRoutes } from "./routes/tasks";
import { registerComplianceRoutes } from "./routes/compliance";
import { registerDocumentRoutes } from "./routes/documents";
import { registerAIRoutes } from "./routes/ai";
import { registerAnalyticsRoutes } from "./routes/analytics";
import { registerAdminRoutes } from "./routes/admin";
import { registerWorkflowRoutes } from "./routes/workflows";
import { registerMarketRoutes } from "./routes/market";
import { registerScenarioRoutes } from "./routes/scenarios";
import { registerSalesforceRoutes } from "./routes/salesforce";
import { registerOrionRoutes } from "./routes/orion";
import { registerMicrosoftRoutes } from "./routes/microsoft";
import { registerZoomRoutes } from "./routes/zoom";
import { registerAlertGenerationRoutes } from "./routes/alert-generation";
import { registerMeetingProcessingRoutes } from "./routes/meeting-processing";
import { registerAssessmentRoutes } from "./routes/assessment";
import { registerInsightsRoutes } from "./routes/insights";
import { registerHealthRoutes } from "./routes/health";
import { registerFeatureFlagRoutes } from "./routes/feature-flags";
import { registerFeedbackRoutes } from "./routes/feedback";
import { registerPilotMetricsRoutes } from "./routes/pilot-metrics";
import { registerProfileRoutes } from "./routes/profiles";
import { registerReminderRoutes } from "./routes/reminders";
import { registerTriggerRoutes } from "./routes/triggers";
import { registerCalendlyRoutes } from "./routes/calendly";
import { registerReportRoutes } from "./routes/reports";
import { registerCalculatorRoutes } from "./routes/calculators";
import { registerCustodialRoutes } from "./routes/custodial";
import { registerApprovalRoutes } from "./routes/approvals";
import { registerFactFinderRoutes } from "./routes/fact-finders";
import { registerCassidyRoutes } from "./routes/cassidy";
import { registerDiscoveryRoutes } from "./routes/discovery";
import { registerEventRoutes } from "./routes/events";
import { registerGoalRoutes } from "./routes/goals";
import { registerOnboardingRoutes } from "./routes/onboarding";
import { registerEstatePlanningRoutes } from "./routes/estate-planning";
import { registerFiduciaryComplianceRoutes } from "./routes/fiduciary-compliance";
import { registerBehavioralFinanceRoutes } from "./routes/behavioral-finance";
import { registerWithdrawalRoutes } from "./routes/withdrawals";
import { registerValidationRoutes } from "./routes/validation";
import { registerSopRoutes } from "./routes/sop";
import { registerKycAmlRoutes } from "./routes/kyc-aml";
import { registerNigoRoutes } from "./routes/nigo";
import { registerEngagementRoutes } from "./routes/engagement";
import { registerPhilanthropyRoutes } from "./routes/philanthropy";
import { registerResearchRoutes } from "./routes/research";
import { registerDirectIndexingRoutes } from "./routes/direct-indexing";
import { registerSocialIntelligenceRoutes } from "./routes/social-intelligence";
import { registerCustodialReportingRoutes } from "./routes/custodial-reporting";
import { registerBusinessSuccessionRoutes } from "./routes/business-succession";
import { registerProfileUpdateRoutes } from "./routes/profile-updates";
import { registerPhilanthropicRoutes } from "./routes/philanthropic";
import { registerCrossModuleIntelligenceRoutes } from "./routes/cross-module-intelligence";
import { registerEstateDocumentRoutes } from "./routes/estate-documents";
import { registerInsuranceRoutes } from "./routes/insurance";
import { registerHouseholdRoutes } from "./routes/households";
import { registerTrustRoutes } from "./routes/trusts";
import { registerCalendarRoutes } from "./routes/calendar";
import { registerDataServiceRoutes } from "./routes/data-services";
import { registerActivityHistoryRoutes } from "./routes/activity-history";
import { registerAuditLogRoutes } from "./routes/audit-log";
import { registerLoginEventRoutes } from "./routes/login-events";
import { registerActivityAnalyticsRoutes } from "./routes/activity-analytics";
import { registerClientInsightsRoutes } from "./routes/client-insights";
import { registerPortfolioRoutes } from "./routes/portfolio";
import { registerWorkflowAutomationRoutes } from "./routes/workflow-automations";
import { registerDataSourceRoutes } from "./routes/data-sources";
import { ensureMeetingLifecycleDefinition } from "./engines/workflow-definitions/meeting-lifecycle";

export async function registerRoutes(
  httpServer: Server,
  app: Express
): Promise<Server> {
  await seedDatabase();

  app.use("/avatars", express.static(path.join(process.cwd(), "attached_assets/avatars")));

  registerHealthRoutes(app);
  registerEventRoutes(app);
  registerAuthRoutes(app);
  registerClientRoutes(app);
  registerMeetingRoutes(app);
  registerTaskRoutes(app);
  registerComplianceRoutes(app);
  registerDocumentRoutes(app);
  registerAIRoutes(app);
  registerAnalyticsRoutes(app);
  registerAdminRoutes(app);
  registerWorkflowRoutes(app);
  registerMarketRoutes(app);
  registerScenarioRoutes(app);
  registerAlertGenerationRoutes(app);
  registerMeetingProcessingRoutes(app);
  registerAssessmentRoutes(app);
  registerInsightsRoutes(app);
  registerSalesforceRoutes(app);
  registerOrionRoutes(app);
  registerMicrosoftRoutes(app);
  registerZoomRoutes(app);
  registerFeatureFlagRoutes(app);
  registerFeedbackRoutes(app);
  registerPilotMetricsRoutes(app);
  registerProfileRoutes(app);
  registerReminderRoutes(app);
  registerTriggerRoutes(app);
  registerCalendlyRoutes(app);
  registerReportRoutes(app);
  registerCalculatorRoutes(app);
  registerApprovalRoutes(app);
  registerCustodialRoutes(app);
  registerFactFinderRoutes(app);
  registerDiscoveryRoutes(app);
  registerCassidyRoutes(app);
  registerGoalRoutes(app);
  registerOnboardingRoutes(app);
  registerEstatePlanningRoutes(app);
  registerFiduciaryComplianceRoutes(app);
  registerBehavioralFinanceRoutes(app);
  registerWithdrawalRoutes(app);
  registerValidationRoutes(app);
  registerSopRoutes(app);
  registerKycAmlRoutes(app);
  registerNigoRoutes(app);
  registerEngagementRoutes(app);
  registerPhilanthropyRoutes(app);
  registerResearchRoutes(app);
  registerDirectIndexingRoutes(app);
  registerSocialIntelligenceRoutes(app);
  registerCustodialReportingRoutes(app);
  registerProfileUpdateRoutes(app);
  registerBusinessSuccessionRoutes(app);
  registerPhilanthropicRoutes(app);
  registerCrossModuleIntelligenceRoutes(app);
  registerEstateDocumentRoutes(app);
  registerInsuranceRoutes(app);
  registerHouseholdRoutes(app);
  registerTrustRoutes(app);
  registerCalendarRoutes(app);
  registerDataServiceRoutes(app);
  registerActivityHistoryRoutes(app);
  registerAuditLogRoutes(app);
  registerLoginEventRoutes(app);
  registerActivityAnalyticsRoutes(app);
  registerClientInsightsRoutes(app);
  registerPortfolioRoutes(app);
  registerWorkflowAutomationRoutes(app);
  registerDataSourceRoutes(app);

  ensureMeetingLifecycleDefinition().catch((err) => {
    console.error("Failed to seed meeting lifecycle definition:", err);
  });

  return httpServer;
}
