import { logger } from "./logger";

export interface GuardrailRule {
  id: string;
  description: string;
  pattern: RegExp;
  severity: "block" | "flag";
  replacement?: string;
}

export interface GuardrailResult {
  passed: boolean;
  flagged: boolean;
  violations: Array<{
    ruleId: string;
    description: string;
    severity: "block" | "flag";
    matchedText: string;
  }>;
  output: string;
  disclaimer: string | null;
}

const DEFAULT_RULES: GuardrailRule[] = [
  {
    id: "guarantee-returns",
    description: "No guarantees of investment returns",
    pattern: /\b(guarantee[ds]?\s+(a\s+)?return|guaranteed\s+(profit|gains?|income)|will\s+(definitely|certainly|absolutely)\s+(earn|make|return|gain|grow)|promise[ds]?\s+(a\s+)?(return|profit|gain))\b/gi,
    severity: "block",
    replacement: "[Past performance does not guarantee future results. Returns are subject to market risk.]",
  },
  {
    id: "specific-security-recommendation",
    description: "No specific security buy/sell recommendations without disclosure",
    pattern: /\b(you\s+should\s+(buy|sell|short|invest\s+in)\s+[A-Z]{1,5}\b|I\s+recommend\s+(buying|selling|investing\s+in)\s+[A-Z]{1,5}\b|must\s+(buy|sell|invest\s+in)\s+[A-Z]{1,5}\b)/gi,
    severity: "flag",
  },
  {
    id: "no-risk-claim",
    description: "No claims of risk-free investments",
    pattern: /\b(risk[\s-]?free\s+(investment|return|income|strategy)|no[\s-]?risk\s+(investment|strategy|approach)|zero[\s-]?risk|without\s+any\s+risk|eliminat(e|es|ing)\s+all\s+risk)\b/gi,
    severity: "block",
    replacement: "[All investments carry risk. There is no risk-free investment strategy.]",
  },
  {
    id: "tax-advice",
    description: "No specific tax advice without CPA disclaimer",
    pattern: /\b(you\s+(will|would)\s+save\s+\$[\d,]+\s+in\s+tax|your\s+tax\s+(bill|liability)\s+will\s+(be|decrease|drop)\s+(to\s+)?\$[\d,]+|guaranteed?\s+tax\s+(savings?|deduction|benefit))\b/gi,
    severity: "flag",
  },
  {
    id: "legal-advice",
    description: "No specific legal advice",
    pattern: /\b(as\s+your\s+(lawyer|attorney)|legal(ly)?\s+(you\s+must|you\s+should|requires?\s+you\s+to)|I\s+am\s+(advising|recommending)\s+you\s+legally)\b/gi,
    severity: "block",
    replacement: "[Please consult a qualified legal professional for legal advice.]",
  },
  {
    id: "insurance-recommendation",
    description: "No specific insurance product recommendations without license disclosure",
    pattern: /\b(you\s+(must|need\s+to|should)\s+(buy|purchase|get)\s+(this|the|a)\s+specific\s+(insurance|policy|plan|coverage))\b/gi,
    severity: "flag",
  },
  {
    id: "market-timing",
    description: "No definitive market timing predictions",
    pattern: /\b(the\s+market\s+will\s+(definitely|certainly|absolutely)\s+(crash|drop|rise|go\s+up|go\s+down|recover|collapse)|stocks?\s+will\s+(definitely|certainly)\s+(go\s+up|go\s+down|crash|double|triple))\b/gi,
    severity: "block",
    replacement: "[Market predictions are inherently uncertain. Past performance does not guarantee future results.]",
  },
  {
    id: "unlicensed-advice",
    description: "No impersonation of licensed professional",
    pattern: /\b(as\s+a\s+(licensed|certified|registered)\s+(advisor|planner|broker)|I\s+am\s+a\s+(CFP|CFA|CPA|licensed\s+advisor))\b/gi,
    severity: "block",
    replacement: "[AI-generated content. Please verify with a qualified professional.]",
  },
];

const FIDUCIARY_DISCLAIMER =
  "This analysis is generated by AI and is for informational purposes only. It does not constitute personalized financial, legal, or tax advice. Past performance does not guarantee future results. All investments carry risk. Please consult with a qualified professional before making financial decisions.";

export function applyFiduciaryGuardrails(
  aiOutput: string,
  customRules?: GuardrailRule[]
): GuardrailResult {
  const rules = customRules || DEFAULT_RULES;
  const violations: GuardrailResult["violations"] = [];
  let output = aiOutput;
  let hasBlockViolation = false;
  let hasFlagViolation = false;

  for (const rule of rules) {
    rule.pattern.lastIndex = 0;
    const matches = aiOutput.match(rule.pattern);
    if (matches) {
      for (const match of matches) {
        violations.push({
          ruleId: rule.id,
          description: rule.description,
          severity: rule.severity,
          matchedText: match.substring(0, 100),
        });
      }

      if (rule.severity === "block" && rule.replacement) {
        rule.pattern.lastIndex = 0;
        output = output.replace(rule.pattern, rule.replacement);
        hasBlockViolation = true;
      } else if (rule.severity === "flag") {
        hasFlagViolation = true;
      }
    }
  }

  const needsDisclaimer = hasBlockViolation || hasFlagViolation;

  if (needsDisclaimer && !output.includes("does not constitute")) {
    output = output + "\n\n---\n*" + FIDUCIARY_DISCLAIMER + "*";
  }

  if (violations.length > 0) {
    logger.warn(
      { violationCount: violations.length, ruleIds: violations.map((v) => v.ruleId) },
      "[FiduciaryGuardrail] Violations detected in AI output"
    );
  }

  return {
    passed: violations.length === 0,
    flagged: hasFlagViolation,
    violations,
    output,
    disclaimer: needsDisclaimer ? FIDUCIARY_DISCLAIMER : null,
  };
}

export function getDefaultRules(): GuardrailRule[] {
  return [...DEFAULT_RULES];
}
